services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a --project kubernetes-udemy-264217
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t elie29/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elie29/react-test:latest npm run test

after_success:
  # build production images: Continuous Integration (CInt) phase
  - docker build -t elie29/multi-client:latest ./client
  - docker build -t elie29/multi-server:latest ./server
  - docker build -t elie29/multi-worker:latest ./worker
  # Continuous Delivery (CDel) Phase
  ## Take those images and push them to docker hub
  - docker push elie29/multi-client:latest
  - docker push elie29/multi-server:latest
  - docker push elie29/multi-worker:latest
